import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Shrista Baruah || Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  )
}
